common: &common
  adapter: postgresql
  encoding: unicode
  username: ariel
  pool: 5

development: &development
  <<: *common
  database: recipe_app_development

test: &test
  <<: *common
  database: recipe_app_test

production: &production
  <<: *common
  database: recipe_app_production

cucumber:
  <<: *test